---
Name: secureassetsroutes
After: '#rootroutes'
---
Folder:
  extensions:
    - ArchiveFolderExtension
File:
  extensions:
    - ArchiveFileExtension
File:
  extensions:
   - ArchiveFileExtension
Director:
  rules:
    'assets': 'ArchiveFileController'
